package day_15_04;

public class Odev {
    /* BILGISAYAR 0-100 ARASINDA BIR SAYI TUTUP, KULLANICIDAN TAHMIN ISTER
     ve KULLANICI SAYIYI BULANA KADAR "DAHA KUCUK VEYA DAHA BUYUK SAYI SÖYLE" DIYE YOL GOSTERIR
     BULUNCA KACINCI TAHMINDE BULDUGUNU YAZAR
     */
}
